server:
    port: 8040
spring:
    application:
        name: gateway-zuul    
eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8084/eureka
management:
    security:
        enabled: false
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
            
        