spring:
    datasource:
        url: jdbc:mysql://127.0.0.1:3306/cloud?characterEncoding=UTF-8
        username: root
        password: 123456
        driver-class-name: com.mysql.jdbc.Driver
    jpa:
        properties:
            hibernate:
                hbm2ddl:
                    auto: update
        show-sql: true   
    application:
        name: provider-user
eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8084/eureka
    instance:
        prefer-ip-address: true                             
server:
    port: 8086
logging:
    level:
        org:
            hibernate:
                SQL: DEBUG