spring:
    application:
        name: file-upload
    http:
        multipart:
            max-file-size: 2000Mb
            max-request-size: 2500Mb   
eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8084/eureka
    instance:
        prefer-ip-address: true                             
server:
    port: 8050
       