server:
    port: 8083
info:
    app:
        name: @project.artifactId@
        encoding: @project.build.sourceEncoding@
        java:
            source: @java.version@
            target: @java.version@
spring:
    application:
        name: consumer-movie    
eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8084/eureka
    instance:
        prefer-ip-address: true                  
logging:
  level:
    feign: DEBUG