server:
    port: 8031       
spring:
    application:
        name: hystrix-turbine
eureka:
    client:
        service-url:
            defaultZone: http://127.0.0.1:8084/eureka
    instance:
        prefer-ip-address: true
turbine:
    appConfig: consumer-movie,consumer-feign-hystrix-fallback-stream
    clusterNameExpression: "'default'"              